### ISSUE TITLE
Failed at Orthophoto building

### ISSUE THREAD

**Issue by Pratyush1991** [OpenDroneMap/node-OpenDroneMap#13]
I took the photos with my iphone5s.  I have attached below the link to my data set.
https://drive.google.com/drive/folders/0B7tV_P5gZivFVU1FbHE1Mjk1Tkk?usp=sharing
I have also tried with other data sets i.e. from DJI Phantom 3 which worked well and results were good.
So I feel may be my iphone datasets doesn't have good overlay. But I have tried this data sets with Agisoft photoscan which could create dense cloud. My objective is to compare both the dense cloud generated from Agisoft Photoscan and WebODM. 
So I will be glad if you could help..:-)

I have pasted below the error log..
Building objmodel:
 Saving model... Building objmodel:
 Saving model... done.
Whole texturing procedure took: 96.698s
[INFO]    Running ODM Texturing Cell - Finished
[INFO]    Running ODM Georeferencing Cell
[DEBUG]   None
[WARNING] No coordinates file. Generating coordinates file: /var/www/data/64e26d38-86c4-4a3a-b234-246a5319e9d8/odm_georeferencing/coords.txt
[WARNING] Could not generate coordinates file. Ignore if there is a GCP file. Error: Error in OdmExtractUtm:
No valid GPS position found
For more detailed information, see log file.

[WARNING] Georeferencing failed. Make sure your photos have geotags in the EXIF or you have provided a GCP file. 
[INFO]    Running ODM Georeferencing Cell - Finished
[INFO]    Running ODM Orthophoto Cell
[DEBUG]   running /code/build/bin/odm_orthophoto -inputFile /var/www/data/64e26d38-86c4-4a3a-b234-246a5319e9d8/odm_texturing/odm_textured_model.obj -logFile /var/www/data/64e26d38-86c4-4a3a-b234-246a5319e9d8/odm_orthophoto/odm_orthophoto_log.txt -outputFile /var/www/data/64e26d38-86c4-4a3a-b234-246a5319e9d8/odm_orthophoto/odm_orthophoto.png -resolution 20.0  -outputCornerFile /var/www/data/64e26d38-86c4-4a3a-b234-246a5319e9d8/odm_orthophoto/odm_orthophoto_corners.txt
[INFO]    OpenDroneMap app finished - Sat May 13 18:38:45  2017
PDAL: No type found for undefined dimension ID.﻿

**Comment by pierotofy** [comment]
Thank you for reporting the problem! I will take a look at it and report back my findings.

**Comment by pierotofy** [comment]
It should be working now if you update the code to the latest version (`docker pull opendronemap/node-opendronemap`)

You won't get good orthophoto results with this dataset however. I'd recommend reading this article and shooting more pictures: http://www.tested.com/art/makers/460142-art-photogrammetry-how-take-your-photos/

**Comment by Pratyush1991** [comment]
Thank a lot..!! It worked.
I will read the article and try with different data sets.
