### ISSUE TITLE
Add lidar2dems to node-OpenDroneMap

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/node-OpenDroneMap#15]
It looks like this package handles the generation of DSM/DTM/CHM in an easy manner. It's based on PCL/PDAL, so it's just a matter of installing it / tying it into the postprocessing.

http://applied-geosolutions.github.io/lidar2dems/

@dakotabenjamin should this be included in ODM?

**Comment by dakotabenjamin** [comment]
I think its worth at least checking out.

**Comment by smathermather** [comment]
Might be worth it for the gapfill flag alone: http://applied-geosolutions.github.io/lidar2dems/doc/concepts

**Comment by pierotofy** [comment]
That's what I was thinking @smathermather

**Comment by pierotofy** [comment]
Without gapfill:

![image](https://cloud.githubusercontent.com/assets/1951843/26325787/55d7b454-3f06-11e7-832a-b190f597486d.png)

With gapfill:

![image](https://cloud.githubusercontent.com/assets/1951843/26325800/6c3e09be-3f06-11e7-9345-ed1fa4230500.png)

Hillshade:

![image](https://cloud.githubusercontent.com/assets/1951843/26325835/91b2d454-3f06-11e7-9adf-29ad6486bd52.png)

**Comment by pierotofy** [comment]
Steps to get up and running on latest OpenDroneMap docker image:

```
git clone https://github.com/pierotofy/lidar2dems/
cd lidar2dems
pip install https://github.com/Applied-GeoSolutions/gippy/archive/v0.3.9.tar.gz
apt-get install -y swig2.0 python-wheel libboost-log-dev libgdal-dev libxslt-dev
CPLUS_INCLUDE_PATH=/usr/include/gdal C_INCLUDE_PATH=/usr/include/gdal ./setup.py install
ln -s /code/SuperBuild/build/pdal/bin/pdal /usr/bin/pdal
```

**Comment by pierotofy** [comment]
DTM/DSM/CHM

![image](https://cloud.githubusercontent.com/assets/1951843/26328051/8d47eb8a-3f0f-11e7-9e5b-a4d33113d355.png)
![image](https://cloud.githubusercontent.com/assets/1951843/26328058/9286aadc-3f0f-11e7-802c-4cb3ef9d148d.png)
![image](https://cloud.githubusercontent.com/assets/1951843/26328112/be765c00-3f0f-11e7-814a-2efd90de6cb8.png)

**Comment by smathermather** [comment]
This is awesome.

**Comment by pierotofy** [comment]
@dakotabenjamin will you have any time to integrate this? Otherwise I can try to find some time myself and open a PR in ODM.

**Comment by dakotabenjamin** [comment]
No I don't think I will have time. Very busy with other things atm, and about to go on vacation.

**Comment by pierotofy** [comment]
Have fun on vacation 😄

**Comment by pierotofy** [comment]
@dakotabenjamin, I'm planning to add the lidar2dems module to ODM core.

Would it be convenient to make a fork of https://github.com/pierotofy/lidar2dems/ under the OpenDroneMap organization so that I can reference that during install?

**Comment by dakotabenjamin** [comment]
This would facilitate a safer update process as we would have more control over when/how to do so, I think that is a good idea.
