### ISSUE TITLE
geotiff process to tiles any idea sir

### ISSUE THREAD

**Issue by boopathit98** [OpenDroneMap/node-OpenDroneMap#17]
hi sir,
geotiff process to tiles any idea please any tutorial sir i will also pay

**Comment by pierotofy** [comment]
Hello @boopathit98, I'm not sure I understand your question. Could you try to rephrase it?

**Comment by boopathit98** [comment]
orthophoto how to process tiles layer in any tutorial links python please helpful for us

**Comment by kikislater** [comment]
Use gdal2tiles or other webmapping technics to generate tiles. In other words, make it with gis
