### ISSUE TITLE
Invalid configuration file config-default.json error

### ISSUE THREAD

**Issue by PeterSprague** [OpenDroneMap/node-OpenDroneMap#33]
Getting error when attempting to run in Docker.  Builds w/o errors.
$ docker run --rm -it --name node-odm-001 gei/opendronemap:nodeodm-nocuda-opencv-3.3.1-amd64.debian-stretch
Invalid configuration file config-default.json

Been through the json file, nothing seems out of kilter.  ODM builds and runs fine.

**Comment by pierotofy** [comment]
Hey @PeterSprague, thanks for reporting the problem.

Does this image work? https://hub.docker.com/r/opendronemap/node-opendronemap/ (it's built from master every night).

**Comment by pierotofy** [comment]
The error is thrown here https://github.com/OpenDroneMap/node-OpenDroneMap/blob/master/config.js#L54 so perhaps the file does not exist in the image you've built?

**Comment by PeterSprague** [comment]
if (/\.json$/i.test(configFilePath)){
	try{
#L54		let data = fs.readFileSync(configFilePath);
		configFile = JSON.parse(data.toString());
	}catch(e){
		console.log(`Invalid configuration file ${configFilePath}`);
		process.exit(1);
	}

fs refers to a nodejs module?

**Comment by pierotofy** [comment]
It's a core module. The npm warnings aren't related.

https://nodejs.org/api/fs.html
