### ISSUE TITLE
change rename calls to move (so that volumes can be mounted)

### ISSUE THREAD

**Issue by madeinoz67** [OpenDroneMap/node-OpenDroneMap#35]
When running using the node container within a docker webodm installation, I'm having issues after uploading images where jobs are failing because of the lack of disk space. where the processing node is filling up after a 2nd or third job that the docker volume this container it's using is filling up and is capping out at 10GB.

I have the web-odm containers  all running on a centos 7.4 docker host.  The underlying docker host has plenty of Disk space - 500GB where I've allocated majority of this to /var/lib/docker.

I'm using the images that are pulled from docker hub.

To get around this I've tried exposing  /var/www/data and /var/www/tmp directories on the node container to the underlying host, but get the following message

`EXDEV: cross-device link not permitted, rename 'tmp/1ce8eb3d-ce5e-43bf-89d8-d22b92a54f3c' -> 'data/1ce8eb3d-ce5e-43bf-89d8-d22b92a54f3c/images'`

however the man for the rename function would indicate that whatever is happening after I upload the images does not like this.

```
EXDEV  oldpath and newpath are not on the same mounted filesystem.
              (Linux permits a filesystem to be mounted at multiple points,
              but rename() does not work across different mount points, even
              if the same filesystem is mounted on both.)
```

so any suggestions on how to get around this would make my life a lot easier or to expand the node volume?

**Comment by madeinoz67** [comment]
Docker host df before task is executed

![2018-03-12_00-34-57](https://user-images.githubusercontent.com/4160293/37261835-407239b6-25da-11e8-9268-6b9c862cb566.png)

Docker df after task has finished
![2018-03-12_09-45-07](https://user-images.githubusercontent.com/4160293/37261837-40c828ee-25da-11e8-9770-37aa518417fc.png)

**Comment by pierotofy** [comment]
I'd suggest increasing `dm.basesize` as a workaround for the moment.

https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-storage-driver

There's been a proposal to change `rename` with some other command that could move files between file systems (so that people could mount a volume), but I don't think anyone had time to contribute to this change yet. I'll leave this open as an improvement.
