### ISSUE TITLE
Work with ODM docker

### ISSUE THREAD

**Issue by hy9be** [OpenDroneMap/node-OpenDroneMap#47]
The document says we can specify the path or ODM using ``--odm_path`` parameter. What if I am using ODM as docker? Is it possible to have node-OpenDroneMap work with an ODM docker? Thanks!

**Comment by pierotofy** [comment]
Hey @hy9be :hand: I'm not entirely sure what you mean by using ODM as docker, perhaps you meant you're using docker for running ODM?

You can certainly use node-OpenDroneMap using docker as well. Just use the `opendronemap/node-opendronemap` image as indicated in the README https://github.com/OpenDroneMap/node-OpenDroneMap. The image already includes OpenDroneMap and you don't need to configure a path with `--odm_path`.

**Comment by pierotofy** [comment]
Go with 1). After you are done making your customizations to node-odm, from the node-odm directory simply run:

`docker build -t hy9be/node-opendronemap .`

Then you can run everything in docker using `hy9be/node-opendronemap` instead of `opendronemap/node-opendronemap`.

**Comment by hy9be** [comment]
@pierotofy get it. Thanks!
