### ISSUE TITLE
starting of server failed

### ISSUE THREAD

**Issue by paulinK** [OpenDroneMap/node-OpenDroneMap#9]
Hello
I'm trying to run node-OpenDroneMap natively. When I run this command 

node index.js --odm_path /home/wedevgroup/WebODM_natif/WebODM , I get this message 

error: Error during startup: Could not load list of options from OpenDroneMap. Is OpenDroneMap installed in /home/wedevgroup/WebODM_natif/WebODM? Make sure that OpenDroneMap is installed and that --odm_path is set properly: Unexpected token T in JSON at position 0

Can someone help me to fix this problem ?
thank!

**Comment by pierotofy** [comment]
Hi PaulinK,

the `--odm_path` refers to the installation of OpenDroneMap (not WebODM). WebODM is an interface to OpenDroneMap. If you want to run node-OpenDroneMap natively, you'll need to get OpenDroneMap to run natively first as well.

See the instructions here: https://github.com/OpenDroneMap/OpenDroneMap

**Comment by paulinK** [comment]
Hi @pierotofy 
I have seen  that and I have tried to install OpenDronMap nativily but when I run 
python run.py --project-path /home/wedevgroup/WebODM_natif/OpenDroneMap/projects/test

I get this error message

Traceback (most recent call last):
  File "run.py", line 8, in <module>
    import ecto
ImportError: No module named ecto

**Comment by pierotofy** [comment]
Did you follow the instructions in the readme to install OpenDroneMap? https://github.com/OpenDroneMap/OpenDroneMap#installation

**Comment by paulinK** [comment]
I have follow these instructions 
https://github.com/OpenDroneMap/OpenDroneMap/tree/ebaaf802a1fb50e335b3807a35d00cba1e106d11#installation

**Comment by paulinK** [comment]
Hi @pierotofy 
When trying the instructions from 

I have got some error 

[ 65%] Completed 'ceres'
[ 65%] Built target ceres
Makefile:83 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2
Compiling build
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   date_time
--   iostreams
--   serialization
--   chrono
--   atomic
--   regex
-- Checking for module 'openni-dev'
--   No package 'openni-dev' found
-- Could NOT find openni (missing:  OPENNI_LIBRARY OPENNI_INCLUDE_DIRS) 
** WARNING ** io features related to openni will be disabled
-- Checking for module 'openni2-dev'
--   No package 'openni2-dev' found
-- Could NOT find OpenNI2 (missing:  OPENNI2_LIBRARY OPENNI2_INCLUDE_DIRS) 
** WARNING ** io features related to openni2 will be disabled
** WARNING ** io features related to pcap will be disabled
** WARNING ** io features related to png will be disabled
-- The imported target "vtkWrapTcl" references the file
   "/usr/bin/vtkWrapTcl"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/vtk-5.10/VTKTargets.cmake"
but not all the files it references.

-- The imported target "vtkWrapTclInit" references the file
   "/usr/bin/vtkWrapTclInit"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/vtk-5.10/VTKTargets.cmake"
but not all the files it references.

-- The imported target "vtkWrapPython" references the file
   "/usr/bin/vtkWrapPython"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/vtk-5.10/VTKTargets.cmake"
but not all the files it references.

I have got many other errors again

**Comment by paulinK** [comment]
Hi
sorry for my many  posts.
When I try to run 
python run.py -i /path/to/images project-name
I get this error message 
 Traceback (most recent call last):
  File "run.py", line 4, in <module>
    from opendm import config
  File "/home/wedevgroup/WebODM_natif/OpenDroneMap-master/opendm/config.py", line 6, in <module>
    from appsettings import SettingsParser
ImportError: No module named appsettings

**Comment by pierotofy** [comment]
Try to run ODM with the `run.sh  -i /path/to/images project-name` script instead of `python run.py ...`. See if that helps!

**Comment by paulinK** [comment]
Hi @pierotofy 
Thank for help. It works fine. 
Now I can try to start node-OpenDroneMap 
thank you

**Comment by paulinK** [comment]
Sorry, I have a question please
Can you tell me the role of node-OpenDroneMap? Why is it so important to use it with WebODM ?
Thank

**Comment by paulinK** [comment]
Sorry @pierotofy 
When trying to lunch a task on WebODM (native installation after installing OpenDroneMap and node-OpenDroneMap), I get this message

Process exited with code 1

and also this message in the areatext 

Traceback (most recent call last):
  File "/home/wedevgroup/WebODM_natif/OpenDroneMapNoyau/run.py", line 8, in <module>
    import ecto
  File "/home/wedevgroup/WebODM_natif/OpenDroneMapNoyau/SuperBuild/install/lib/python2.7/dist-packages/ecto/__init__.py", line 30, in <module>
    from ecto.ecto_main import _cell_base, _cell_cpp, __getitem_list__, __getitem_slice__, __getitem_str__, __getitem_tuple__, lookup
ImportError: libecto.so.0.6: cannot open shared object file: No such file or directory


Can you give me an idea to fix it please 
thank you

**Comment by gkconsulting** [comment]
Hi @paulinK 
I'm very new to this but I ran into a similar issue and found that if I start up node-OpenDroneMap with sudo, then I must also start WebODM as sudo else it can't find the libraries. 
What version of Linux are you running?
If you not going to be running the server as a production (opening it up to the internet), I found that running everything as root (sudo su) seems to work with no issues. I'm not sure if this is correct (as I said, I'm new to all this) but I hope that it helps.

**Comment by thomstarnes** [comment]
I'm getting the same error:

  File "/home/thomas/Downloads/OpenDroneMap_v0_3_1/opendm/config.py", line 6, in <module>
    from appsettings import SettingsParser
ImportError: No module named appsettings

Running ODM with the ./run.sh -i /path/to/images project-name script instead of python run.py is producing the same error.
